language: node_js
node_js:
- "4.6.0"
- "5.12.0"
- "6.12.0"
- "7.10.1"
- "8.9.1"
- "9.2.0"
after_script:
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
